use revera::config::Config;
use revera::diff::parse_unified;
use revera::pipeline::common::{prepare, PrepareOut, ReviewRequest};
use revera::triage::{triage, RiskTier, SkipReason, TriageConfig};
use std::io::Write;
use std::path::Path;
use std::process::Command;

/// A unified diff modifying `path` with `adds` added lines starting at line 10.
fn modified(path: &str, adds: usize) -> String {
    let body: String = (0..adds).map(|i| format!("+let v{i} = {i};\n")).collect();
    format!(
        "diff --git a/{path} b/{path}\n--- a/{path}\n+++ b/{path}\n@@ -10,1 +10,{} @@\n ctx\n{body}",
        adds + 1
    )
}

/// A unified diff adding `path` whose first line is `header`.
fn added(path: &str, header: &str) -> String {
    format!(
        "diff --git a/{path} b/{path}\nnew file mode 100644\n--- /dev/null\n+++ b/{path}\n@@ -0,0 +1,2 @@\n+{header}\n+body\n"
    )
}

fn skipped(text: &str, cfg: &TriageConfig) -> Vec<(String, SkipReason)> {
    triage(parse_unified(text), cfg)
        .unwrap()
        .skipped
        .into_iter()
        .map(|s| (s.path, s.reason))
        .collect()
}

#[test]
fn noise_files_are_dropped_and_reported() {
    let text = [
        modified("Cargo.lock", 40),
        modified("web/app.min.js", 3),
        modified("web/app.js.map", 3),
        modified("vendor/lib/x.go", 3),
        added("src/schema_pb.rs", "// @generated by protoc. DO NOT EDIT."),
        modified("src/lib.rs", 2),
    ]
    .concat();
    let t = triage(parse_unified(&text), &TriageConfig::default()).unwrap();
    let kept: Vec<&str> = t.diff.files.iter().map(|f| f.new_path.as_str()).collect();
    assert_eq!(kept, vec!["src/lib.rs"]);
    let reasons: Vec<SkipReason> = t.skipped.iter().map(|s| s.reason).collect();
    assert_eq!(
        reasons,
        vec![
            SkipReason::Lockfile,
            SkipReason::Minified,
            SkipReason::SourceMap,
            SkipReason::Vendored,
            SkipReason::Generated,
        ]
    );
    // only reviewed lines count toward the tier: the 40-line lockfile does not
    assert_eq!(t.changed_lines, 2);
    assert_eq!(t.tier, RiskTier::Trivial);
}

#[test]
fn generated_migrations_are_still_reviewed() {
    let text = added("db/migrations/0042_users.sql", "-- @generated by migrate");
    assert!(skipped(&text, &TriageConfig::default()).is_empty());
}

#[test]
fn generated_marker_below_header_is_not_noise() {
    // a marker deep in the file is content, not a generated-file header
    let text = "diff --git a/src/a.rs b/src/a.rs\n--- a/src/a.rs\n+++ b/src/a.rs\n@@ -40,1 +40,2 @@\n ctx\n+// DO NOT EDIT this constant\n";
    assert!(skipped(text, &TriageConfig::default()).is_empty());
}

#[test]
fn filter_noise_off_keeps_noise_but_honours_ignore_paths() {
    let cfg = TriageConfig {
        filter_noise: false,
        ignore_paths: vec!["docs/**".into()],
        ..Default::default()
    };
    let text = [modified("Cargo.lock", 3), modified("docs/guide.md", 3)].concat();
    assert_eq!(
        skipped(&text, &cfg),
        vec![("docs/guide.md".to_string(), SkipReason::Ignored)]
    );
}

#[test]
fn tiers_follow_size_and_file_count() {
    let cfg = TriageConfig::default();
    let tier = |text: String| triage(parse_unified(&text), &cfg).unwrap().tier;
    assert_eq!(tier(modified("src/a.rs", 10)), RiskTier::Trivial);
    assert_eq!(tier(modified("src/a.rs", 11)), RiskTier::Lite);
    assert_eq!(tier(modified("src/a.rs", 100)), RiskTier::Lite);
    assert_eq!(tier(modified("src/a.rs", 101)), RiskTier::Full);
    let many: String = (0..21)
        .map(|i| modified(&format!("src/m{i}.rs"), 1))
        .collect();
    assert_eq!(tier(many), RiskTier::Full);
}

#[test]
fn sensitive_paths_force_full_tier() {
    let t = triage(
        parse_unified(&modified("src/auth/login.rs", 1)),
        &TriageConfig::default(),
    )
    .unwrap();
    assert_eq!(t.tier, RiskTier::Full);
    assert_eq!(t.sensitive, vec!["src/auth/login.rs".to_string()]);

    let cfg = TriageConfig {
        sensitive_paths: vec!["billing/**".into()],
        ..Default::default()
    };
    let t = triage(parse_unified(&modified("billing/charge.rs", 1)), &cfg).unwrap();
    assert_eq!(t.tier, RiskTier::Full);
}

fn write_config(triage_yaml: &str) -> tempfile::NamedTempFile {
    let mut f = tempfile::NamedTempFile::new().unwrap();
    write!(
        f,
        "models:\n  investigator: {{protocol: scripted, script: /tmp/s.json, model: m}}\n{triage_yaml}"
    )
    .unwrap();
    f
}

#[test]
fn config_rejects_invalid_triage_settings() {
    let bad_glob = write_config("triage: {ignore_paths: [\"src/[\"]}\n");
    let e = Config::load(bad_glob.path()).unwrap_err();
    assert!(format!("{e:#}").contains("triage.ignore_paths"), "{e:#}");

    let inverted = write_config("triage: {trivial_max_lines: 50, lite_max_lines: 20}\n");
    let e = Config::load(inverted.path()).unwrap_err();
    assert!(e.to_string().contains("trivial_max_lines"), "{e}");

    let zero_lanes = write_config("triage: {lite_max_lanes: 0}\n");
    assert!(Config::load(zero_lanes.path()).is_err());

    let unknown = write_config("triage: {filter_nosie: false}\n");
    assert!(Config::load(unknown.path()).is_err());
}

#[test]
fn triage_settings_change_the_review_identity() {
    let a = Config::load(write_config("").path()).unwrap();
    let b = Config::load(write_config("triage: {ignore_paths: [\"docs/**\"]}\n").path()).unwrap();
    assert_ne!(a.review_fingerprint("panel"), b.review_fingerprint("panel"));
}

fn git(repo: &Path, args: &[&str]) -> String {
    let out = Command::new("git")
        .args([
            "-c",
            "user.email=t@t",
            "-c",
            "user.name=t",
            "-c",
            "commit.gpgsign=false",
        ])
        .args(args)
        .current_dir(repo)
        .output()
        .unwrap();
    assert!(
        out.status.success(),
        "git {args:?}: {}",
        String::from_utf8_lossy(&out.stderr)
    );
    String::from_utf8(out.stdout).unwrap().trim().to_string()
}

#[tokio::test]
async fn prepare_hides_noise_from_reviewers_and_reports_it() {
    let dir = tempfile::tempdir().unwrap();
    let repo = dir.path();
    git(repo, &["init", "-q", "-b", "main"]);
    std::fs::create_dir_all(repo.join("src")).unwrap();
    std::fs::write(repo.join("src/lib.rs"), "pub fn f() {}\n").unwrap();
    std::fs::write(repo.join("Cargo.lock"), "version = 3\n").unwrap();
    git(repo, &["add", "."]);
    git(repo, &["commit", "-q", "-m", "base"]);
    let base = git(repo, &["rev-parse", "HEAD"]);
    std::fs::write(repo.join("src/lib.rs"), "pub fn f() -> u8 { 1 }\n").unwrap();
    std::fs::write(repo.join("Cargo.lock"), "version = 4\n").unwrap();
    git(repo, &["commit", "-q", "-am", "change"]);

    let cfg: Config = serde_yaml::from_str(
        "models:\n  investigator: {protocol: scripted, script: /tmp/s.json, model: m}\ntriage: {risk_tiers: true}\n",
    )
    .unwrap();
    let req = ReviewRequest {
        repo: repo.to_path_buf(),
        base: base.clone(),
        head: None,
        title: None,
        body: String::new(),
        strategy_override: None,
        force: true,
        uncommitted: false,
    };
    let prep = match prepare(&cfg, &req, "panel").await.unwrap() {
        PrepareOut::Ready(p) => p,
        PrepareOut::ShortCircuit(..) => panic!("unexpected short circuit"),
    };
    let paths: Vec<&str> = prep
        .diff
        .files
        .iter()
        .map(|f| f.new_path.as_str())
        .collect();
    assert_eq!(paths, vec!["src/lib.rs"]);
    assert_eq!(prep.coverage_gaps.len(), 1);
    assert!(
        prep.coverage_gaps[0].contains("Cargo.lock"),
        "{:?}",
        prep.coverage_gaps
    );
    assert_eq!(prep.stats.filtered_files, 1);
    assert_eq!(prep.risk_tier, Some(RiskTier::Trivial));

    // an explicit --strategy override opts out of tier downgrades
    let overridden = ReviewRequest {
        strategy_override: Some(revera::config::Strategy::Panel),
        ..req
    };
    let prep = match prepare(&cfg, &overridden, "panel").await.unwrap() {
        PrepareOut::Ready(p) => p,
        PrepareOut::ShortCircuit(..) => panic!("unexpected short circuit"),
    };
    assert_eq!(prep.risk_tier, None);
}

/// Commit a change of `lines` added lines to src/lib.rs on top of a base
/// commit; returns (tempdir, base sha).
fn repo_with_change(lines: usize) -> (tempfile::TempDir, String) {
    let dir = tempfile::tempdir().unwrap();
    let repo = dir.path();
    git(repo, &["init", "-q", "-b", "main"]);
    std::fs::create_dir_all(repo.join("src")).unwrap();
    std::fs::write(repo.join("src/lib.rs"), "pub fn f() {}\n").unwrap();
    git(repo, &["add", "."]);
    git(repo, &["commit", "-q", "-m", "base"]);
    let base = git(repo, &["rev-parse", "HEAD"]);
    let body: String = (0..lines)
        .map(|i| format!("pub const C{i}: u8 = {i};\n"))
        .collect();
    std::fs::write(repo.join("src/lib.rs"), format!("pub fn f() {{}}\n{body}")).unwrap();
    git(repo, &["commit", "-q", "-am", "change"]);
    (dir, base)
}

async fn panel_note(lines: usize, risk_tiers: bool) -> (String, Option<String>) {
    let (dir, base) = repo_with_change(lines);
    let script = dir.path().join("script.json");
    std::fs::write(&script, r#"{"roles": {}}"#).unwrap();
    let cfg: Config = serde_yaml::from_str(&format!(
        "review: {{strategy: panel, validate: false}}\npanel: {{focuses: [security, correctness, performance]}}\nmodels:\n  investigator: {{protocol: scripted, script: {}, model: m}}\ntriage: {{risk_tiers: {risk_tiers}}}\n",
        script.display()
    ))
    .unwrap();
    let req = ReviewRequest {
        repo: dir.path().to_path_buf(),
        base,
        head: None,
        title: None,
        body: String::new(),
        strategy_override: None,
        force: true,
        uncommitted: false,
    };
    let (rep, _) = revera::pipeline::run(&cfg, &req).await.unwrap();
    (rep.plan.summary_markdown, rep.stats.risk_tier)
}

#[tokio::test]
async fn trivial_change_runs_one_investigator_instead_of_the_panel() {
    let (summary, tier) = panel_note(2, true).await;
    assert_eq!(tier.as_deref(), Some("trivial"));
    assert!(
        summary.contains("risk tier trivial: single investigator instead of the panel swarm"),
        "{summary}"
    );
    assert!(!summary.contains("scouts"), "{summary}");
}

#[tokio::test]
async fn lite_change_caps_panel_lanes() {
    let (summary, tier) = panel_note(20, true).await;
    assert_eq!(tier.as_deref(), Some("lite"));
    assert!(summary.contains("panel: 2 scouts"), "{summary}");
    assert!(
        summary.contains("risk tier lite: 1 lane(s) not run"),
        "{summary}"
    );
}

#[tokio::test]
async fn tiers_off_runs_the_full_panel() {
    let (summary, tier) = panel_note(2, false).await;
    assert_eq!(tier, None);
    assert!(summary.contains("panel: 3 scouts"), "{summary}");
}

#[tokio::test]
async fn files_past_the_prompt_budget_are_reported_as_gaps() {
    let (dir, base) = repo_with_change(30);
    let cfg: Config = serde_yaml::from_str(
        "review: {max_diff_bytes: 64}\nmodels:\n  investigator: {protocol: scripted, script: /tmp/s.json, model: m}\n",
    )
    .unwrap();
    let req = ReviewRequest {
        repo: dir.path().to_path_buf(),
        base,
        head: None,
        title: None,
        body: String::new(),
        strategy_override: None,
        force: true,
        uncommitted: false,
    };
    let prep = match prepare(&cfg, &req, "baseline").await.unwrap() {
        PrepareOut::Ready(p) => p,
        PrepareOut::ShortCircuit(..) => panic!("unexpected short circuit"),
    };
    assert_eq!(
        prep.diff.omitted_by_budget(64),
        vec!["src/lib.rs".to_string()]
    );
    assert!(
        prep.coverage_gaps
            .iter()
            .any(|g| g.contains("`src/lib.rs`") && g.contains("max_diff_bytes")),
        "{:?}",
        prep.coverage_gaps
    );
    // the default budget holds the whole diff, so nothing is reported
    assert!(prep.diff.omitted_by_budget(200_000).is_empty());
}

#[test]
fn credential_files_are_withheld_even_with_noise_filter_off() {
    let cfg = TriageConfig {
        filter_noise: false,
        ..Default::default()
    };
    let text = [
        modified(".npmrc", 1),
        modified("config/.env.production", 1),
        modified("deploy/server.key", 1),
        modified("home/.ssh/config", 1),
        modified(".env.example", 1),
        modified("src/keys.rs", 1),
    ]
    .concat();
    let t = triage(parse_unified(&text), &cfg).unwrap();
    let withheld: Vec<&str> = t
        .withheld
        .files
        .iter()
        .map(|f| f.new_path.as_str())
        .collect();
    assert_eq!(
        withheld,
        vec![
            ".npmrc",
            "config/.env.production",
            "deploy/server.key",
            "home/.ssh/config"
        ]
    );
    let kept: Vec<&str> = t.diff.files.iter().map(|f| f.new_path.as_str()).collect();
    assert_eq!(kept, vec![".env.example", "src/keys.rs"]);
    assert!(t.skipped.iter().all(|s| s.reason == SkipReason::Credential));
}

#[tokio::test]
async fn committed_secret_in_a_credential_file_is_reported_without_its_content() {
    let dir = tempfile::tempdir().unwrap();
    let repo = dir.path();
    git(repo, &["init", "-q", "-b", "main"]);
    std::fs::write(repo.join("README.md"), "x\n").unwrap();
    git(repo, &["add", "."]);
    git(repo, &["commit", "-q", "-m", "base"]);
    let base = git(repo, &["rev-parse", "HEAD"]);
    std::fs::write(
        repo.join(".npmrc"),
        "registry=x\n//r/:_authToken=AKIAIOSFODNN7EXAMPLE\n",
    )
    .unwrap();
    git(repo, &["add", "."]);
    git(repo, &["commit", "-q", "-m", "creds"]);
    let cfg: Config = serde_yaml::from_str(
        "models:\n  investigator: {protocol: scripted, script: /tmp/s.json, model: m}\n",
    )
    .unwrap();
    let req = ReviewRequest {
        repo: repo.to_path_buf(),
        base,
        head: None,
        title: None,
        body: String::new(),
        strategy_override: None,
        force: true,
        uncommitted: false,
    };
    let prep = match prepare(&cfg, &req, "baseline").await.unwrap() {
        PrepareOut::Ready(p) => p,
        PrepareOut::ShortCircuit(..) => panic!("unexpected short circuit"),
    };
    assert!(prep.diff.files.is_empty());
    let gap = prep.coverage_gaps.join("\n");
    assert!(gap.contains("`.npmrc` (credential file"), "{gap}");
    assert!(gap.contains("line(s) 2"), "{gap}");
    assert!(!gap.contains("AKIA"), "{gap}");
    let read = prep
        .toolbox
        .call("read_file", serde_json::json!({"path": ".npmrc"}))
        .await;
    assert!(!read.contains("AKIA"), "{read}");
}
