//! Deterministic diff triage, run before any model sees the change: drop
//! files no reviewer should spend tokens on (lockfiles, minified bundles,
//! source maps, vendored and generated code, user-ignored globs) and size
//! the remaining change into a risk tier that decides how many reviewers run.

use crate::diff::{DiffLineKind, DiffSet, FileDiff, FileStatus};
use anyhow::{bail, Context, Result};
use globset::{Glob, GlobSet, GlobSetBuilder};
use serde::{Deserialize, Serialize};

/// Dependency lockfiles, matched on the file name.
const LOCKFILES: &[&str] = &[
    "Cargo.lock",
    "package-lock.json",
    "npm-shrinkwrap.json",
    "yarn.lock",
    "pnpm-lock.yaml",
    "bun.lock",
    "bun.lockb",
    "go.sum",
    "poetry.lock",
    "Pipfile.lock",
    "uv.lock",
    "pdm.lock",
    "flake.lock",
    "composer.lock",
    "Gemfile.lock",
    "Podfile.lock",
    "Package.resolved",
    "packages.lock.json",
    "pubspec.lock",
    "mix.lock",
    "gradle.lockfile",
];

const MINIFIED_SUFFIXES: &[&str] = &[".min.js", ".min.mjs", ".min.css", ".bundle.js"];

/// Extensions whose `.map` companions are build artefacts.
const SOURCE_MAP_TARGETS: &[&str] = &[".js", ".mjs", ".cjs", ".css", ".ts"];

/// Path segments that hold third-party code checked into the repository.
const VENDOR_SEGMENTS: &[&str] = &[
    "vendor",
    "node_modules",
    "third_party",
    "third-party",
    ".yarn",
];

/// Header markers of generated files; only looked for in the first lines.
const GENERATED_MARKERS: &[&str] = &[
    "@generated",
    "do not edit",
    "code generated by",
    "autogenerated",
    "auto-generated",
];
const GENERATED_HEADER_LINES: u32 = 5;

/// Path fragments that always force a full review, whatever the diff size.
const SENSITIVE_FRAGMENTS: &[&str] = &[
    "auth",
    "crypto",
    "security",
    "secret",
    "credential",
    "password",
    "permission",
    "oauth",
    "jwt",
    "session",
    "sandbox",
    ".github/workflows/",
];

/// Above this many reviewed files a change is always full.
const SMALL_MAX_FILES: usize = 20;

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(deny_unknown_fields)]
pub struct TriageConfig {
    /// Drop lockfiles, minified bundles, source maps, vendored and
    /// generated files before review.
    #[serde(default = "default_true")]
    pub filter_noise: bool,
    /// Extra globs never sent for review (applied even with `filter_noise` off).
    #[serde(default)]
    pub ignore_paths: Vec<String>,
    /// Size the reviewer swarm by risk tier (panel and delegated strategies).
    #[serde(default)]
    pub risk_tiers: bool,
    /// Extra globs that force a full review on top of the built-in list.
    #[serde(default)]
    pub sensitive_paths: Vec<String>,
    #[serde(default = "default_trivial_max_lines")]
    pub trivial_max_lines: usize,
    #[serde(default = "default_lite_max_lines")]
    pub lite_max_lines: usize,
    /// Panel lanes kept for a lite change, in configured order.
    #[serde(default = "default_lite_max_lanes")]
    pub lite_max_lanes: usize,
}

fn default_true() -> bool {
    true
}
fn default_trivial_max_lines() -> usize {
    10
}
fn default_lite_max_lines() -> usize {
    100
}
fn default_lite_max_lanes() -> usize {
    2
}

impl Default for TriageConfig {
    fn default() -> Self {
        Self {
            filter_noise: true,
            ignore_paths: vec![],
            risk_tiers: false,
            sensitive_paths: vec![],
            trivial_max_lines: default_trivial_max_lines(),
            lite_max_lines: default_lite_max_lines(),
            lite_max_lanes: default_lite_max_lanes(),
        }
    }
}

impl TriageConfig {
    pub fn validate(&self) -> Result<()> {
        build_globs("triage.ignore_paths", &self.ignore_paths)?;
        build_globs("triage.sensitive_paths", &self.sensitive_paths)?;
        if self.trivial_max_lines > self.lite_max_lines {
            bail!(
                "triage.trivial_max_lines ({}) must not exceed triage.lite_max_lines ({})",
                self.trivial_max_lines,
                self.lite_max_lines
            );
        }
        if self.lite_max_lanes == 0 {
            bail!("triage.lite_max_lanes must be at least 1");
        }
        Ok(())
    }
}

fn build_globs(field: &str, globs: &[String]) -> Result<GlobSet> {
    let mut b = GlobSetBuilder::new();
    for g in globs {
        b.add(Glob::new(g).with_context(|| format!("{field}: invalid glob {g:?}"))?);
    }
    b.build()
        .with_context(|| format!("{field}: cannot compile globs"))
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum RiskTier {
    Trivial,
    Lite,
    Full,
}

impl RiskTier {
    pub fn as_str(self) -> &'static str {
        match self {
            Self::Trivial => "trivial",
            Self::Lite => "lite",
            Self::Full => "full",
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum SkipReason {
    Lockfile,
    Minified,
    SourceMap,
    Vendored,
    Generated,
    Ignored,
}

impl SkipReason {
    pub fn as_str(self) -> &'static str {
        match self {
            Self::Lockfile => "lockfile",
            Self::Minified => "minified",
            Self::SourceMap => "source map",
            Self::Vendored => "vendored",
            Self::Generated => "generated",
            Self::Ignored => "triage.ignore_paths",
        }
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Skipped {
    pub path: String,
    pub reason: SkipReason,
}

#[derive(Debug, Clone)]
pub struct Triage {
    /// The diff with skipped files removed: what the reviewers see.
    pub diff: DiffSet,
    pub skipped: Vec<Skipped>,
    pub tier: RiskTier,
    /// Added plus deleted lines across the reviewed files.
    pub changed_lines: usize,
    /// Reviewed paths that forced the full tier.
    pub sensitive: Vec<String>,
}

/// The path a file is known by on the side that exists after the change.
fn file_path(f: &FileDiff) -> &str {
    if f.status == FileStatus::Deleted {
        &f.old_path
    } else {
        &f.new_path
    }
}

fn file_name(path: &str) -> &str {
    path.rsplit('/').next().unwrap_or(path)
}

fn is_migration(path: &str) -> bool {
    path.to_ascii_lowercase().contains("migration")
}

fn has_generated_header(f: &FileDiff) -> bool {
    f.hunks.iter().flat_map(|h| &h.lines).any(|l| {
        l.kind != DiffLineKind::Del && l.new_no.is_some_and(|n| n <= GENERATED_HEADER_LINES) && {
            let t = l.text.to_ascii_lowercase();
            GENERATED_MARKERS.iter().any(|m| t.contains(m))
        }
    })
}

fn noise_reason(f: &FileDiff) -> Option<SkipReason> {
    let path = file_path(f);
    let name = file_name(path);
    let lower = name.to_ascii_lowercase();
    if LOCKFILES.contains(&name) {
        return Some(SkipReason::Lockfile);
    }
    if MINIFIED_SUFFIXES.iter().any(|s| lower.ends_with(s)) {
        return Some(SkipReason::Minified);
    }
    if let Some(stem) = lower.strip_suffix(".map") {
        if SOURCE_MAP_TARGETS.iter().any(|s| stem.ends_with(s)) {
            return Some(SkipReason::SourceMap);
        }
    }
    if path.split('/').any(|seg| VENDOR_SEGMENTS.contains(&seg)) {
        return Some(SkipReason::Vendored);
    }
    // migration tools stamp their output as generated, but schema changes
    // are exactly what a reviewer must see
    if !is_migration(path) && has_generated_header(f) {
        return Some(SkipReason::Generated);
    }
    None
}

fn is_sensitive(path: &str, extra: &GlobSet) -> bool {
    let lower = path.to_ascii_lowercase();
    SENSITIVE_FRAGMENTS.iter().any(|s| lower.contains(s)) || extra.is_match(path)
}

fn changed_lines(f: &FileDiff) -> usize {
    f.hunks
        .iter()
        .flat_map(|h| &h.lines)
        .filter(|l| l.kind != DiffLineKind::Ctx)
        .count()
}

/// Split `diff` into the files to review and the files skipped as noise,
/// then classify the reviewed part into a risk tier.
pub fn triage(diff: DiffSet, cfg: &TriageConfig) -> Result<Triage> {
    let ignore = build_globs("triage.ignore_paths", &cfg.ignore_paths)?;
    let sensitive_globs = build_globs("triage.sensitive_paths", &cfg.sensitive_paths)?;
    let mut kept = Vec::with_capacity(diff.files.len());
    let mut skipped = vec![];
    for f in diff.files {
        let path = file_path(&f);
        let reason = if ignore.is_match(path) {
            Some(SkipReason::Ignored)
        } else if cfg.filter_noise {
            noise_reason(&f)
        } else {
            None
        };
        match reason {
            Some(reason) => skipped.push(Skipped {
                path: path.to_string(),
                reason,
            }),
            None => kept.push(f),
        }
    }
    let lines: usize = kept.iter().map(changed_lines).sum();
    let sensitive: Vec<String> = kept
        .iter()
        .map(file_path)
        .filter(|p| is_sensitive(p, &sensitive_globs))
        .map(str::to_string)
        .collect();
    let files = kept.len();
    let tier = if !sensitive.is_empty() || files > SMALL_MAX_FILES {
        RiskTier::Full
    } else if lines <= cfg.trivial_max_lines {
        RiskTier::Trivial
    } else if lines <= cfg.lite_max_lines {
        RiskTier::Lite
    } else {
        RiskTier::Full
    };
    Ok(Triage {
        diff: DiffSet { files: kept },
        skipped,
        tier,
        changed_lines: lines,
        sensitive,
    })
}
